old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbitmq_host%'
            user: '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost: '%rabbitmq_statuslayer_vhost%'
    producers:
        emailing:
            connection: default
            exchange_options: { name: 'emails' , type: direct}
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
    consumers:
        emailing:
            connection: default
            exchange_options: { name: 'emails', type: direct }
            queue_options: { name: 'emails' }
            callback: App\Consumer\EmailsConsumer

        emailing2:
            connection: default
            exchange_options: { name: 'emails', type: direct }
            queue_options: { name: 'emails2' }
            callback: App\Consumer\EmailsConsumer
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
