# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'ru'
    knp_menu.renderer.twig.options:
        currentClass: active
    rabbitmq_host: 'rabbit-mq'
    rabbitmq_user: 'my_username'
    rabbitmq_password: '12345'
    rabbitmq_statuslayer_vhost: 'taskman42'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - ['pass properties as array']

    app.menu_builder.service:
        class: App\Menu\Builder
        arguments: ['@knp_menu.factory']
        tags:
            - { name: 'knp_menu.menu_builder', method: 'mainMenu', alias: 'main'}

    app.project_rights_hierarchy:
        class: App\Hierarchy\ProjectRightsHierarchy

    App\EventSubscriber\InviteUsersSubscriber:
        arguments: ['@old_sound_rabbit_mq.emailing_producer']
        autowire: false
        tags:
            - { name: 'kernel.event_subscriber', priority: -100 }


    App\Repository\ProjectRepository:
        arguments: ['@doctrine', '@sb_redis.default']
        public: true